# Generated by Django 5.1.2 on 2024-11-12 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Updated_at',
            new_name='updated_at',
        ),
    ]
